# Generated by Django 3.0.1 on 2019-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='place_id',
        ),
        migrations.AddField(
            model_name='event',
            name='place_name',
            field=models.CharField(default='Harbour Bar & Kitchen', max_length=100),
            preserve_default=False,
        ),
    ]
