# Generated by Django 3.0.1 on 2020-01-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20200105_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_profiles/'),
        ),
    ]
